### ISSUE TITLE
Add a MapView for Chronicle Queue

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Engine#12]
The MapView would have a key and an index to the queue entry.

Add the option to migrate values after a roll. e.g. after a cycle roll, migrate all keys older than a cycle (the one before the previous cycle)

**Comment by RobAustin** [comment]
Is this not just chronicle-journal, and as such, I think, this change should go in its own project, perhaps an enterprise project at that. In other words, I don think we should bloat chronicle queue with this )

**Comment by peter-lawrey** [comment]
From a design point of view, I don't think queue should depend on engine.
This could be added to engine as we should only do a trivial implementation
in the OS version.
A more efficient native version should be in something like Journal +
closed source.

**Comment by RobAustin** [comment]
done see tests - QueueAsMapView and for replication ( in enterprise queue ) - software.chronicle.enterprise.queue.ReplicatedQueueAsMapViewTest
