### ISSUE TITLE
Add Chronicle-Websocket-Jetty integration for Chronicle Engine.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Engine#13]
Support access to queues and maps via web sockets, with a sample program in Java Websockets and JavaScript.

This will help demonstrate Engine as an API Gateway http://microservices.io/patterns/apigateway.html

e.g.  
- attach to an asset via URL
- publish messages and enable subscriptions via JSON commands.

Later I would like to be able to bind to an actor/value in a map or queue and issue method calls.

**Comment by RobAustin** [comment]
@peter-lawrey is this something that you still want done, especially now that we are moving to chronicle-services. I don't think this is a priority any more, so will move it to "wont fix" and close it. Please re-open if you disagree.

**Comment by peter-lawrey** [comment]
I think this should be integrated with Chronicle Services when we have use
case to do so.
ᐧ
