### ISSUE TITLE
QueueEvents

### ISSUE THREAD

**Issue by pistolla** [OpenHFT/Chronicle-Engine#14]
Hi Peter Lawrey, i love chronicle queue and i dont have a way to catch add,  update, delete events.

**Comment by peter-lawrey** [comment]
Chronicle Queue is an append only queue which is a history of what has
happened.  You can append a new event but you cannot change the past. You
can only add more events to replave or reverse a action.

Can you clarify your question?

**Comment by pistolla** [comment]
Thats why its a queue,  i get it.  i am experimenting with map and it seems i can listen to events on the concurrent map.  I am using the queue as shared memory between daemon process and javafx UI. my logic is well structured in that a single queue store events as objects. The ui checks on new events from daemon and maybe writes into the queue when ui has new events. i dont know how to make it reactive although im having an idea of polling using timer

**Comment by pistolla** [comment]
BTW thanks for the microservice, it works and its efficient

**Comment by peter-lawrey** [comment]
You can poll it periodically or use a LongPauser to control the interval.

**Comment by pistolla** [comment]
Thanks
