### ISSUE TITLE
SubscriptionEventTest fails intermittently 

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Engine#15]
http://teamcity.higherfrequencytrading.com:8111/viewLog.html?buildId=152603&tab=buildResultsDiv&buildTypeId=OpenHFT_ChronicleEngine_Snapshot#testNameId6397772949067718713

and

http://teamcity.higherfrequencytrading.com:8111/viewLog.html?buildId=152313&tab=buildResultsDiv&buildTypeId=OpenHFT_ChronicleEngine_Snapshot

**Comment by RobAustin** [comment]
this test has been run in all the latest team-city builds and passes, so I am closing this issue.
