### ISSUE TITLE
JDK 9 support

### ISSUE THREAD

**Issue by johnpoth** [OpenHFT/Chronicle-Engine#19]
The project currently fails on JDK 9:

```
java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner;
```

To reproduce:

```
   @Test
    public void testMapEvents() throws Exception {
        net.openhft.chronicle.bytes.NativeBytesStore.elasticByteBuffer(256, 1024);
    }
```

If a more elaborate test is required you can checkout [ChronicleEngineConsumerTest](https://github.com/apache/camel/blob/cf9dc8da481e232df0359f53ae609d120501246f/components/camel-chronicle/src/test/java/org/apache/camel/component/chronicle/engine/ChronicleEngineConsumerTest.java).

Thanks!

**Comment by MartyIX** [comment]
I can confirm the issue.

**Comment by MartyIX** [comment]
https://bugs.openjdk.java.net/browse/JDK-8148117 - it seems the class was just renamed from `sun.misc.Cleaner` to `jdk.internal.ref.Clearer`

**Comment by MartyIX** [comment]
I was able to compile Chronicle-Bytes project using the following command:

$ /c/Work/Programs/apache-maven-3.5.0/bin/mvn -Dmaven.test.skip=true  -Dmaven.compiler.fork=true -Dmaven.compiler.executable=/c/work/Programs/jdk-9.176/bin/javac clean package

with the following patch:

```
$ git diff
diff --git a/pom.xml b/pom.xml
index 3bc5450..69d558c 100755
--- a/pom.xml
+++ b/pom.xml
@@ -131,11 +131,16 @@
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-compiler-plugin</artifactId>
+                <version>3.6.1</version>
                 <configuration>
                     <compilerArgument>-Xlint:deprecation</compilerArgument>
-                    <source>1.8</source>
-                    <target>1.8</target>
+                    <source>1.9</source>
+                    <target>1.9</target>
                     <encoding>UTF-8</encoding>
+                    <compilerArgs>
+                        <arg>--add-exports</arg><arg>java.base/jdk.internal.ref=ALL-UNNAMED</arg>
+                        <arg>--add-exports</arg><arg>java.base/sun.nio.ch=ALL-UNNAMED</arg>
+                    </compilerArgs>
                 </configuration>
             </plugin>
             <!--
@@ -161,6 +166,7 @@
             <plugin>
                 <groupId>org.apache.felix</groupId>
                 <artifactId>maven-bundle-plugin</artifactId>
+                <version>3.3.0</version>
                 <extensions>true</extensions>
                 <configuration>
                     <instructions>
diff --git a/src/main/java/net/openhft/chronicle/bytes/NativeBytesStore.java b/src/main/java/net/openhft/chronicle/bytes/NativeBytesStore.java
index a1fee5e..14baa2b 100755
--- a/src/main/java/net/openhft/chronicle/bytes/NativeBytesStore.java
+++ b/src/main/java/net/openhft/chronicle/bytes/NativeBytesStore.java
@@ -23,7 +23,7 @@ import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
-import sun.misc.Cleaner;
+import jdk.internal.ref.Cleaner;
 import sun.misc.Unsafe;
 import sun.nio.ch.DirectBuffer;
```

My goal was to only compile the project for JDK 9. Nothing more.

**Comment by MartyIX** [comment]
After digging deeper, I've found out that Java 9 support seems to be an enterprise feature: https://github.com/OpenHFT/Chronicle-Core/blob/master/src/main/java/net/openhft/chronicle/core/OS.java#L140

My attempts to run Chronicle Queue with Java 9 failed at:

```
Exception in thread "Thread-1" java.lang.ClassCastException: [B cannot be cast to [C                                
        at net.openhft.chronicle.core.util.StringUtils.extractChars(StringUtils.java:125)                                                
        at net.openhft.chronicle.bytes.BytesInternal.parse8bit_SB1(BytesInternal.java:429)                                                 
        at net.openhft.chronicle.bytes.AppendableUtil.parse8bit_SB1(AppendableUtil.java:194)                       
        at net.openhft.chronicle.bytes.AppendableUtil.parse8bit(AppendableUtil.java:203)
        at net.openhft.chronicle.bytes.StreamingDataInput.read8bit(StreamingDataInput.java:224)
        at net.openhft.chronicle.wire.BinaryWire.readSpecialField(BinaryWire.java:637)
        at net.openhft.chronicle.wire.BinaryWire.readField(BinaryWire.java:597)
```
(https://github.com/OpenHFT/Chronicle-Core/blob/master/src/main/java/net/openhft/chronicle/core/util/StringUtils.java#L125)

@epickrram @peter-lawrey Is Java 9 support an enterprise feature?

**Comment by MartyIX** [comment]
Ah, I start to understand the difference between JDK 8 and JDK 9 and why it fails. The line https://github.com/OpenHFT/Chronicle-Core/blob/master/src/main/java/net/openhft/chronicle/core/util/StringUtils.java#L43

```
SB_VALUE = Class.forName("java.lang.AbstractStringBuilder").getDeclaredField("value");
```

The line above references `value` field. The field is `char[]` in JDK 8 \[[source](https://github.com/dmlloyd/openjdk/blob/jdk9/jdk9/jdk/src/java.base/share/classes/java/lang/AbstractStringBuilder.java)\], yet it is `byte[]` in JDK 9 \[[source](https://github.com/dmlloyd/openjdk/blob/jdk8u/jdk8u/jdk/src/share/classes/java/lang/AbstractStringBuilder.java
)\]. I believe the change in JDK 9 implementation is because of compact string feature that is new in JDK 9 ([JEP 254](http://openjdk.java.net/jeps/254))

**Comment by peter-lawrey** [comment]
I agree. Most likely we will need to wrap up the caller to have two
implementations for char[] and byte[].
ᐧ

**Comment by remkop** [comment]
What is the status on Java 9 and Java 11 support?
Is there any documentation on which version of Chronicle-<component> can be used on which version of Java?

**Comment by remkop** [comment]
@RobAustin  Could you please point me to some docs that clarify which version of Chronicle-`<component>` can be used on which version of Java? Or just say there are no such docs if there aren't any?

**Comment by RobAustin** [comment]
There are no docs, but all versions from
```
 <artifactId>chronicle-bom</artifactId>
  <version>2.17.0</version>
```
and onwards shold work in 9 and 11 Java projects

**Comment by dpisklov** [comment]
Just to add more clarification - Chronicle does NOT support Java 9 officially. We support Java 8 and Java 11 only (i.e. LTS releases only)

**Comment by remkop** [comment]
Thanks for the clarification!
