### ISSUE TITLE
Not authorized , ReasonPhrase:Unauthorized

### ISSUE THREAD

**Issue by zmyer** [OpenHFT/Chronicle-Engine#20]
[ERROR] Failed to execute goal on project chronicle-engine: Could not resolve dependencies for project net.openhft:chronicle-engine:bundle:1.14.2-SNAPSHOT: Failed to collect dependencies at net.openhft:chronicle-queue:jar:4.6.2: Failed to read artifact descriptor for net.openhft:chronicle-queue:jar:4.6.2: Could not transfer artifact net.openhft:chronicle-queue:pom:4.6.2 from/to chronicle-enterprise-snapshots (http://nexus.chronicle.software/content/repositories/snapshots): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

**Comment by dpisklov** [comment]
Please read our policy on open source publishing here: https://github.com/OpenHFT/Chronicle-Queue#download
