### ISSUE TITLE
AssetTree Interface question

### ISSUE THREAD

**Issue by chriskurzeja** [OpenHFT/Chronicle-Engine#21]
I've been taking a look at Chronicle-Engine - in particular the QueueView - and noticed something I just wanted to double check. 

The following two default methods are declared - they are completely identical except for the ordering of the variables. Is there any particular reason for this?

```
    @NotNull
    default <T, M> QueueView<T, M> acquireQueue(@NotNull String uri, Class<T> typeClass, Class<M>
            messageClass, final String cluster, String basePath) {

        @NotNull final RequestContext requestContext = requestContext(uri).basePath(basePath);

        if (requestContext.bootstrap() != null)
            throw new UnsupportedOperationException("Its not possible to set the bootstrap when " +
                    "acquiring a queue");

        return acquireView(requestContext.view("queue").type(typeClass).type2(messageClass)
                .cluster(cluster));
    }

    @NotNull
    default <T, M> QueueView<T, M> acquireQueue(@NotNull String uri, String basePath, Class<T> typeClass,
                                                Class<M> messageClass, final String cluster) {

        @NotNull final RequestContext requestContext = requestContext(uri).basePath(basePath);

        if (requestContext.bootstrap() != null)
            throw new UnsupportedOperationException("Its not possible to set the bootstrap when " +
                    "acquiring a queue");

        return acquireView(requestContext.view("queue").type(typeClass).type2(messageClass)
                .cluster(cluster));
    }
```

**Comment by peter-lawrey** [comment]
Hello,
I suspect the first one should be deprecated and call the second one.

Regards,
   Peter,
ᐧ

**Comment by chriskurzeja** [comment]
Thanks Peter. 

As a side note, I was having trouble getting the demo to work using tagged release of Chronicle-Engine 1.13.27 (we're using this version as we're just in the initial phases of experimentation so haven't got access to later versions). 

I'm running via IntelliJ with the classpath set to the chronicle-engine-demo module so it's picking up this [engine.yaml](https://github.com/OpenHFT/Chronicle-Engine/blob/chronicle-engine-1.13.27/demo/src/main/resources/engine.yaml).

DemoMapListener/DemoMapProducer can't connect to the Engine started by RunEngineMain, see the logging below from Listener:
```
WARN net.openhft.chronicle.network.connection.FatalFailureConnectionStrategy - unable to connected to localhost/127.0.0.1:8088 - localhost:8088, name=/
```

I was able to get this to work by re-adding the server config removed in [this commit](https://github.com/OpenHFT/Chronicle-Engine/commit/d872b1d26dd23d1b475aa1849cd405fbe96fbf95)

My question is this: was it an accidental removal of that config or was this deliberate? If the latter is there some additional config that's not referred to in the demo docs? As an aside, NFS mounting works fine (albeit with some errors thrown on macOS Sierra) but again with the caveat that the previous configuration is added back into the engine.yaml file.
