### ISSUE TITLE
Chronicle-Engine Demo not working

### ISSUE THREAD

**Issue by chriskurzeja** [OpenHFT/Chronicle-Engine#22]
As a side note, I was having trouble getting the demo to work using tagged release of Chronicle-Engine 1.13.27 (we're using this version as we're just in the initial phases of experimentation so haven't got access to later versions via the private repository). 

I'm running via IntelliJ with the classpath set to the chronicle-engine-demo module so it's picking up this [engine.yaml](https://github.com/OpenHFT/Chronicle-Engine/blob/chronicle-engine-1.13.27/demo/src/main/resources/engine.yaml).

DemoMapListener/DemoMapProducer can't connect to the Engine started by RunEngineMain, see the logging below from Listener:
```
WARN net.openhft.chronicle.network.connection.FatalFailureConnectionStrategy - unable to connected to localhost/127.0.0.1:8088 - localhost:8088, name=/
```

I was able to get this to work by re-adding the server config removed in [this commit](https://github.com/OpenHFT/Chronicle-Engine/commit/d872b1d26dd23d1b475aa1849cd405fbe96fbf95)

My question is this: was it an accidental removal of that config or was this deliberate? If the latter is there some additional config that's not referred to in the demo docs? 

NFS mounting is also not working in the demo unless you restore the dependency to chronicle-engine-nfs and re-add the NfsCfg.class removed from RunEngineMain and restore the NfsConfig into the demo engine.yaml.

**Comment by dpisklov** [comment]
@chriskurzeja  I have fixed this in latest snapshot version of Chronicle-Engine (`1.14.12-SNAPSHOT`). Server config has been deliverately removed but the main class hasn't beenc hanged accordingly. Now listener/publisher work fine.
NFS support has been removed from engine due to lack of demand.
Apologise for delay in response.
