### ISSUE TITLE
running demo

### ISSUE THREAD

**Issue by brw31415** [OpenHFT/Chronicle-Engine#6]
hi, can you tell me how to run the demo? i have this cloned to linux. thanks!

**Comment by peter-lawrey** [comment]
I would start by running the unit tests.

What would you like to see?

Regards, Peter.

**Comment by brw31415** [comment]
not being in this field, i'd like to get a general idea of what going on at
first, or maybe everything. ,i'm trying to learn more about reactive
programming than just for ui, which is all i've been learning at this point
(rxjs)

main motivation - a potential client/employer in this area, i might try to
show him. of course trading applications are a fascinating area in their
own right, but there are always also other possible applications for high
performance systems like this

i'm doing this cli in linux do i just configure pom.xml to run these tests?
i don't see much documentation on your site, and maven docs are always a
bit dreary

thanks!

**Comment by peter-lawrey** [comment]
You should be able to run maven test from your IDE provided it is set up
correctly. There is no special instructions required for any of our
projects.
If you want to see how a test runs or performs you should be able to pick a
test, right click and run it just like any unit test.

Regards, Peter.

**Comment by brw31415** [comment]
(master) $ mvn test
[INFO] Scanning for projects...
[INFO]
------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Engine
[INFO]    task-segment: [test]
[INFO]
------------------------------------------------------------------------
[INFO] [enforcer:enforce {execution: enforce-no-snapshots}]
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 201 source files to
/home/ubuntu/workspace/Chronicle-Engine/target/classes
[INFO]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/query/Operation.java:
Some input files use unchecked or unsafe operations.
[INFO]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/query/Operation.java:
Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/map/ChronicleMapKeyValueStore.java:[234,111]
wireType() in net.openhft.chronicle.engine.api.tree.RequestContext has been
deprecated
[WARNING]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/map/ChronicleMapKeyValueStore.java:[236,53]
wireType() in net.openhft.chronicle.engine.api.tree.RequestContext has been
deprecated
[WARNING]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/map/VanillaStringMarshallableKeyValueStore.java:[71,33]
wireType() in net.openhft.chronicle.engine.api.tree.RequestContext has been
deprecated
[INFO] 3 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/api/tree/Asset.java:[20,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: package net.openhft.chronicle.core.util
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/api/tree/Asset.java:[344,23]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: interface net.openhft.chronicle.engine.api.tree.Asset
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[23,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: package net.openhft.chronicle.core.util
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[321,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: class net.openhft.chronicle.engine.tree.VanillaAsset
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaSubAsset.java:[20,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: package net.openhft.chronicle.core.util
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaSubAsset.java:[189,30]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: class net.openhft.chronicle.engine.tree.VanillaSubAsset<E>
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[451,26]
invalid method reference
  non-static method close() cannot be referenced from a static context
[ERROR]
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[465,26]
invalid method reference
  non-static method notifyClosing() cannot be referenced from a static
context
[INFO] 8 errors
[INFO] -------------------------------------------------------------
[INFO]
------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Compilation failure

/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/api/tree/Asset.java:[20,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: package net.openhft.chronicle.core.util
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/api/tree/Asset.java:[344,23]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: interface net.openhft.chronicle.engine.api.tree.Asset
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[23,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: package net.openhft.chronicle.core.util
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[321,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: class net.openhft.chronicle.engine.tree.VanillaAsset
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaSubAsset.java:[20,39]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: package net.openhft.chronicle.core.util
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaSubAsset.java:[189,30]
cannot find symbol
  symbol:   class ThrowingAcceptor
  location: class net.openhft.chronicle.engine.tree.VanillaSubAsset<E>
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[451,26]
invalid method reference
  non-static method close() cannot be referenced from a static context
/home/ubuntu/workspace/Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/tree/VanillaAsset.java:[465,26]
invalid method reference
  non-static method notifyClosing() cannot be referenced from a static
context

[INFO]
------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO]
------------------------------------------------------------------------
[INFO] Total time: 19 seconds
[INFO] Finished at: Tue Jun 14 02:08:49 UTC 2016
[INFO] Final Memory: 43M/988M
[INFO]
------------------------------------------------------------------------

**Comment by peter-lawrey** [comment]
Can you check you have the latest version of the code? It is compiling now.
Or you could use the most recent release version.

**Comment by peter-lawrey** [comment]
This code has been released a number of times since this issue was raised, so it should be compiling now.
