### ISSUE TITLE
Replication tests not shutting down cleanly

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Engine#7]
Replication3WayIntIntTest leaves a RCEventHnalder still running after shutdown.

**Comment by RobAustin** [comment]
this test was being ignored by team city, with a "@Ignore("TODO FIX Engine#10")" 

I've removed this ignore, to see if we can reproduce the issue, as I've not been able to reproduce it locally.

**Comment by RobAustin** [comment]
this test looks to be passing in team city now so I'll close this issue, we can always re-open it again if necessary.
